# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  storytellerbot:
    image: storytellerbot
    build:
      context: .
      dockerfile: src/StorytellerBot/Dockerfile
    ports:
      - 5000:5000
    environment:
      - BotToken=${BOT_TOKEN}
      - HostAddress=${HOST_ADDRESS}
      - WebhookToken=${WEBHOOK_TOKEN}
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ./src/StorytellerBot/logs:/app/logs
      - ./src/StorytellerBot/media:/app/media
      - ./src/StorytellerBot/scripts:/app/scripts
      - ./src/StorytellerBot/db:/app/db:rw
